export const WHATSAPP_NUMBER = "5491100000000"; // ← Cambiá este número

export const products = [
  {
    id: 1,
    name: "Maceta Cilíndrica Texturada",
    subtitle: "Concreto artesanal",
    price: "$8.500",
    image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    tag: "Más vendido",
    delay: "7 a 10 días hábiles",
    description: "Pieza cilíndrica de concreto texturado, ideal para plantas de interior. Cada unidad es única por la naturaleza del material. Incluye orificio de drenaje y tapón de silicona.",
    details: ["Diámetro: 12 cm", "Altura: 15 cm", "Tapón de drenaje incluido", "Acabado sellado al agua"],
    tones: [
      { id: "natural", label: "Natural", color: "#b5aca0" },
      { id: "blanco", label: "Blanco Pulido", color: "#e8e3dd" },
      { id: "negro", label: "Negro Mate", color: "#2c2b29" },
      { id: "terracota", label: "Terracota", color: "#b5613a" },
    ],
  },
  {
    id: 2,
    name: "Bandeja Ovalada Terra",
    subtitle: "Arcilla quemada",
    price: "$12.000",
    image: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    tag: "Nuevo",
    delay: "7 a 10 días hábiles",
    description: "Bandeja ovalada de arcilla natural, perfecta como centro de mesa o para organizar el escritorio con elegancia. Resistente al uso cotidiano.",
    details: ["40 × 22 cm", "Apta para interiores", "Resistente a la humedad", "Bordes irregulares (efecto artesanal)"],
    tones: [
      { id: "crudo", label: "Crudo", color: "#d4c5b0" },
      { id: "arena", label: "Arena", color: "#c9b99a" },
      { id: "cafe", label: "Café Oscuro", color: "#6b4c3b" },
    ],
  },
  {
    id: 3,
    name: "Set Portavelas Geométrico",
    subtitle: "Concreto · Set x3",
    price: "$9.200",
    image: "https://images.unsplash.com/photo-1603006905003-be475563bc59?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    tag: null,
    delay: "5 a 7 días hábiles",
    description: "Set de tres portavelas de formas geométricas distintas. Diseñados para usarse juntos o por separado. Crean una atmósfera cálida y sofisticada.",
    details: ["3 tamaños incluidos", "Para velas estándar y de té", "Acabado natural sin sellar", "Peso aprox. 800 g c/u"],
    tones: [
      { id: "natural", label: "Natural", color: "#b5aca0" },
      { id: "blanco", label: "Blanco", color: "#e8e3dd" },
    ],
  },
  {
    id: 4,
    name: "Centro de Mesa Minimalista",
    subtitle: "Yeso y detalle de mármol",
    price: "$15.500",
    image: "https://images.unsplash.com/photo-1615873968403-89e068629265?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    tag: "A pedido",
    delay: "10 a 15 días hábiles",
    description: "Pieza central de alto impacto para mesa de comedor o living. Diseño orgánico asimétrico con detalles en mármol natural. Casi una obra de autor.",
    details: ["Largo ~45 cm (variable)", "Incluye detalle de mármol", "Requiere cuidados especiales", "Pieza única"],
    tones: [
      { id: "blanco", label: "Blanco Vintage", color: "#f0ebe3" },
      { id: "gris", label: "Gris Perla", color: "#c4bfbb" },
      { id: "marfil", label: "Marfil", color: "#e8dfc8" },
      { id: "negro", label: "Negro Mate", color: "#2c2b29" },
    ],
  },
  {
    id: 5,
    name: "Jarrones Dúo Orgánico",
    subtitle: "Concreto pigmentado · Par",
    price: "$18.000",
    image: "https://images.unsplash.com/photo-1612196808214-b7e239e5f5a4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    tag: "Nuevo",
    delay: "7 a 10 días hábiles",
    description: "Par de jarrones de formas orgánicas e irregulares. No son simétricos por diseño — cada uno tiene su propia personalidad. Para flores secas o frescas.",
    details: ["Alturas: 22 cm y 17 cm", "Boca estrecha (3 cm)", "Para flores secas o frescas", "Cada par es único"],
    tones: [
      { id: "natural", label: "Natural", color: "#b5aca0" },
      { id: "negro", label: "Negro Mate", color: "#2c2b29" },
      { id: "terracota", label: "Terracota", color: "#b5613a" },
    ],
  },
  {
    id: 6,
    name: "Plato Decorativo Artesanal",
    subtitle: "Arcilla blanca · Varios tamaños",
    price: "$7.800",
    image: "https://images.unsplash.com/photo-1567225557594-88d73e55f2cb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    tag: null,
    delay: "5 a 7 días hábiles",
    description: "Plato decorativo de arcilla blanca con texturas hechas a mano. Ideal para entrada, baño o como soporte de objetos pequeños. Estilo wabi-sabi.",
    details: ["Diámetro: 20 cm", "Apto para baño", "Bordes texturizados a mano", "Sellado para humedad"],
    tones: [
      { id: "crudo", label: "Crudo", color: "#d4c5b0" },
      { id: "blanco", label: "Blanco Nieve", color: "#f5f2ee" },
    ],
  },
];